name: Build Frontend

on:
  push:
    branches:
      - main
    # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@8.15.9 --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker
        run: |
          docker build -t tongjiann/kuwei-frontend:latest .

      - name: Push Docker
        run: |
          docker push tongjiann/kuwei-frontend:latest

      - name: send info to ding
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: https://api.xiw.world/api/msg/send?msg=kuwei-frontend%E9%95%9C%E5%83%8F%E6%8E%A8%E9%80%81%E5%AE%8C%E6%88%90
          # Should log the response
          log-response: true
          timeout: 20000
